# Generated by Django 4.2.2 on 2023-07-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('scheduling', models.CharField(max_length=100, verbose_name='Scheduling')),
                ('information', models.CharField(verbose_name='Information')),
                ('vendorContact', models.CharField(verbose_name='VendorContact')),
                ('img', models.CharField(blank=True, default=' ', max_length=250, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('information', models.CharField(verbose_name='Information')),
                ('configuration', models.CharField(verbose_name='Configuration')),
                ('img', models.CharField(blank=True, default=' ', max_length=250, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='router',
            name='name',
        ),
        migrations.AddField(
            model_name='router',
            name='configuration',
            field=models.CharField(blank=True, default='', verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='router',
            name='img',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='router',
            name='information',
            field=models.CharField(blank=True, default='', verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='router',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='router',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title'),
        ),
    ]
