# Generated by Django 4.2.2 on 2023-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_documetation_switch_remove_router_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='configuration',
            field=models.CharField(blank=True, default='', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='information',
            field=models.CharField(blank=True, default='', verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title'),
        ),
    ]
